apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mongodb-atlas-basic
  description: Basic MongoDB project,cluster and endpoint 
spec:
  type: database
  owner: dev-team
  lifecycle: production
